### ISSUE TITLE
JUnit Tests

### ISSUE THREAD

**Issue by Woaf** [Woaf/JPaint#12]

**Comment by Woaf** [comment]
Test cases: (test the JPaintFrame class)
- checking the contents and visibility of contents of a newly opened JPaint window. 
- checking the contents and visibility of contents of the JPaint window, when a new canvas is created. 
++(smaller tests for checking which tool or color is selected)
@Woofthecat

**Comment by Woofthecat** [comment]
I've accidentally used another account to commit and push.
Some tests had been written, and the class got a `@FixMethodOrder` annotation, so it'll execute them in lexicographic order (based on the test name). If anyone would like to write more tests please keep this in mind.

I also had to modify the JPaintFrame class a bit, to be able to create a canvas that can be used during testing.

**Comment by Woaf** [comment]
Cannot build the project. `org.junit.FixMethodOrder` and `org.junit.FixMethodOrder` imports cannot be found by NetBeans.

**Comment by Woofthecat** [comment]
FixMethodOrder is available from JUnit 4.1.1.
Which version are you using?

**Comment by Woaf** [comment]
![image](https://cloud.githubusercontent.com/assets/9072892/26286533/3fbca984-3e68-11e7-96f1-f7181e57f509.png)

**Comment by Woofthecat** [comment]
My bad, I wanted to write 4.11.
Can you update it from 4.10 to 4.11 or 4.12?

Hm. `Help -> Check for Updates` maybe will fix this for you.

**Comment by Woaf** [comment]
Works on NetBeans IDE 8.1, but not on 8.0.2.
